name: lime-format

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: opensauce04/lime3ds-build:latest
      options: -u 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clang format
        env:
          COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
        run: ./.ci/clang-format.sh
